Hillel_hm8_django/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

apps/logger_middleware/urls.py
from django.urls import path
from apps.logger_middleware.views import (
    list_of_requests,
    user_list_of_requests,
    session_list_of_requests,
    requests_menu,
)


app_name = "requests"

urlpatterns = [
    path("requests_menu", requests_menu, name="requests_menu"),
    path("requests_list/all", list_of_requests, name="list_of_requests"),
    path("requests_list/user", user_list_of_requests, name="user_list_of_requests"),
    path("requests_list/session", session_list_of_requests, name="session_list_of_requests"),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("accounts/", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls),
    path("first_example/", include("apps.first_example.urls")),
    path("contacts/", include("apps.contacts.urls")),
    path("sessions_example/", include("apps.sessions_example.urls")),
    path("users/", include("apps.users.urls")),
    path("requests/", include("apps.logger_middleware.urls")),
    path("", include("apps.first_example.root_urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/logger_middleware/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class RequestsLogger(models.Model):
    path = models.CharField(max_length=255)
    user = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=False,
    )

    session_key = models.CharField(max_length=255, null=True)
    counter_of_visits = models.PositiveIntegerField(default=1)
    last_visit = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.user} | {self.path} | {self.session_key}"

    def update_log(self):
        self.counter_of_visits += 1
        self.last_visit = models.DateTimeField(auto_now=True)
        self.save()

apps/logger_middleware/views.py
from django.shortcuts import render
from .models import RequestsLogger


def requests_menu(request):
    return render(request=request, template_name="logger_middleware/requests_menu.html")


def list_of_requests(request):
    context = {
        "object_list": RequestsLogger.objects.all(),
        "count_of_visits": RequestsLogger.objects.all().count(),
    }

    return render(
        request=request,
        template_name="logger_middleware/list_of_logs.html",
        context=context,
    )


def user_list_of_requests(request):
    context = {
        "object_list": RequestsLogger.objects.filter(user=request.user),
        "count_of_visits": RequestsLogger.objects.filter(user=request.user).count(),
    }
    return render(
        request=request,
        template_name="logger_middleware/user_list_of_logs.html",
        context=context,
    )


def session_list_of_requests(request):
    session_key = request.session.session_key

    context = {
        "object_list": RequestsLogger.objects.filter(session_key=session_key),
        "count_of_visits": RequestsLogger.objects.filter(session_key=session_key).count(),
    }
    return render(
        request=request,
        template_name="logger_middleware/session_list_of_logs.html",
        context=context,
    )

apps/templates/logger_middleware/list_of_logs.html
{% extends '_helpers/_base.html' %}

{% block content %}
<ol>
    <h3>You have visited {{ count_of_visits }} pages</h3>
    {% for request in object_list %}
        <li>
        {% if request.user %}
            <p> User: {{ request.user }} </p>
        {% else %}:
            <p>User: Unknown</p>
        {% endif %}
            <p> Path: {{ request.path }} </p>
        {% if request.session_key %}
            <p> Session_key: {{ request.session_key }} </p>
        {% else %}
            <p>Session_key: unknown</p>
        {% endif %}
        </li>
    {% endfor %}
</ol>
{% endblock %}

apps/templates/logger_middleware/requests_menu.html
{% extends '_helpers/_base.html' %}

{% block content %}
    <div class="my-elements-contols">

                    <a href="{% url 'requests:list_of_requests' %}">
                        <button class="btn btn-info">
                            All requests logs
                        </button>
                    </a>
    </div>
    {% if user.is_authenticated %}
    <div class="my-elements-contols">

                    <a href="{% url 'requests:user_list_of_requests' %}">
                        <button class="btn btn-info">
                            User's requests logs
                        </button>
                    </a>
    </div>
    {% endif %}
    <div class="my-elements-contols">

                    <a href="{% url 'requests:session_list_of_requests' %}">
                        <button class="btn btn-info">
                            Session's requests logs
                        </button>
                    </a>
    </div>
{% endblock %}

apps/templates/logger_middleware/session_list_of_logs.html
{% extends '_helpers/_base.html' %}

{% block content %}
<ol>

    <h3>You have visited {{ count_of_visits }} pages</h3>

    {% for request in object_list %}
        <li>
        {% if request.user %}
            <p> User: {{ request.user }} </p>
        {% else %}:
            <p>User: Unknown</p>
        {% endif %}
            <p> Path: {{ request.path }} </p>
        {% if request.session_key %}
            <p> Session_key: {{ request.session_key }} </p>
        {% else %}
            <p>Session_key: unknown</p>
        {% endif %}
        </li>
    {% endfor %}
</ol>
{% endblock %}

apps/templates/logger_middleware/user_list_of_logs.html
{% extends '_helpers/_base.html' %}

{% block content %}
<ol>

    <h3>You have visited {{ count_of_visits }} pages</h3>

    {% for request in object_list %}
        <li>
        {% if request.user %}
            <p> User: {{ request.user }} </p>
        {% else %}:
            <p>User: Unknown</p>
        {% endif %}
            <p> Path: {{ request.path }} </p>
        {% if request.session_key %}
            <p> Session_key: {{ request.session_key }} </p>
        {% else %}
            <p>Session_key: unknown</p>
        {% endif %}
        </li>
    {% endfor %}
</ol>
{% endblock %}