Hillel_hm8_django/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

apps/contacts/urls.py
from django.urls import path
from apps.contacts import views


app_name = "contacts"

urlpatterns = [
    path("contacts_list", views.list_of_contacts, name="contacts_list"),
    path("contact_details/<int:pk>", views.ContactDetailView.as_view(), name="contact_detail"),
    path("contact_create", views.ContactCreateView.as_view(), name="contact_create"),
    path("contact_update/<int:pk>", views.ContactUpdateView.as_view(), name="contact_update"),
    path("contact_delete/<int:pk>", views.ContactDeleteView.as_view(), name="contact_delete"),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("accounts/", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls),
    path("first_example/", include("apps.first_example.urls")),
    path("contacts/", include("apps.contacts.urls")),
    path("sessions_example/", include("apps.sessions_example.urls")),
    path("users/", include("apps.users.urls")),
    path("requests/", include("apps.logger_middleware.urls")),
    path("", include("apps.first_example.root_urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/contacts/models.py
from django.db import models


class Department(models.Model):
    name = models.CharField(max_length=100)

    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    __repr__ = __str__


class Contact(models.Model):
    user_name = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=100)

    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    is_auto_generated = models.BooleanField(default=False)

    department = models.ForeignKey(
        Department,
        on_delete=models.CASCADE,
        related_name="contacts",
        default=None,
        null=True,
        blank=False,
    )

    photo = models.ImageField(
        max_length=255,
        upload_to="contacts/contact/photo",
        blank=True,
        null=True,
    )

    def __str__(self):
        return f"Name: {self.user_name} - phone number: {self.phone_number}"

    __repr__ = __str__

apps/contacts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from apps.contacts.models import Contact
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView


def list_of_contacts(request):
    return render(
        request=request, template_name="contacts/contacts_list.html", context={"object_list": Contact.objects.all()}
    )


class ContactListView(ListView):
    model = Contact


class ContactDetailView(DetailView):
    model = Contact


class ContactCreateView(CreateView):
    model = Contact
    fields = (
        "user_name",
        "department",
        "phone_number",
        "photo",
        "is_auto_generated",
    )

    success_url = reverse_lazy("contacts:contacts_list")


class ContactUpdateView(UpdateView):
    model = Contact
    fields = (
        "user_name",
        "department",
        "phone_number",
        "photo",
        "is_auto_generated",
    )

    success_url = reverse_lazy("contacts:contacts_list")


class ContactDeleteView(DeleteView):
    model = Contact

    success_url = reverse_lazy("contacts:contacts_list")

apps/templates/contacts/contact_confirm_delete.html
{% extends '_helpers/_base.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ object }} ?"</p>
        <button type="submit" class="btn btn-danger">
            Delete
        </button>
    </form>
        <a href="{% url 'contacts:contacts_list' %}">
            <button class="btn btn-secondary">
                Return
            </button>
        </a>
{% endblock %}

apps/templates/contacts/contact_detail.html
{% extends '_helpers/_base.html' %}

{% block content %}
    <h1>Full info about {{ object.user_name }}</h1>
    <p>Name : {{ object.user_name }}</p>
    <p>Department: {{ object.department }}</p>
    <p>Phone number : {{ object.phone_number }}</p>
    <p>Is auto generated : {{ object.is_auto_generated }}</p>
    <p>Created at : {{ object.created_at }}</p>
    <p>Modified at : {{ object.modified_at }}</p>

    <a href="{% url 'contacts:contacts_list' %}">
        <button class="btn btn-secondary">
            Return
        </button>
    </a>
{% endblock %}

apps/templates/contacts/contact_form.html
{% extends '_helpers/_base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy}}
        <button type="submit" class="btn btn-success">
            Submit
        </button>
    </form>
{% endblock %}

apps/templates/contacts/contacts_list.html
{% extends '_helpers/_base.html' %}

{% block content %}
    <a href="{% url 'contacts:contact_create' %}">
        <button class="btn btn-primary">
            Create new contact
        </button>
    </a>
    <ol>
        {% for contact in object_list %}
            <li>
            <div class="my-element-style">
            <div class="my-photo">
                {% if contact.photo %}
                    <img src="{{ contact.photo.url }}" alt="Photo">
                {% endif %}
            </div>

                <p>{{ contact.user_name }}</p>

                {% if contact.department is not None%}
                    <p>Department: {{ contact.department }}</p>
                {% endif %}
                <p>Phone number: {{ contact.phone_number }}</p>
            </div>

                <div class="my-elements-contols">

                    <a href="{% url 'contacts:contact_update' pk=contact.id %}">
                        <button class="btn btn-warning">
                            Edit
                        </button>
                    </a>

                    <a href="{% url 'contacts:contact_delete' pk=contact.id %}">
                       <button class="btn btn-danger">
                           Delete
                       </button>
                    </a>

                    <a href="{% url 'contacts:contact_detail' pk=contact.id %}">
                        <button class="btn btn-info">
                            Full info
                        </button>
                    </a>

                </div>
            </li>
        {% endfor %}
    </ol>
{% endblock %}