Hillel_hm8_django/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

apps/users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginFormView.as_view(), name="login"),
    path("signup/", views.RegisterFormView.as_view(), name="signup"),
    path("update_profile/<int:pk>", views.UserUpdateView.as_view(), name="update_profile"),
    path("profile/<int:pk>", views.UserDetailView.as_view(), name="profile"),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("accounts/", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls),
    path("first_example/", include("apps.first_example.urls")),
    path("contacts/", include("apps.contacts.urls")),
    path("sessions_example/", include("apps.sessions_example.urls")),
    path("users/", include("apps.users.urls")),
    path("requests/", include("apps.logger_middleware.urls")),
    path("", include("apps.first_example.root_urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/users/models.py
from django.contrib.auth.models import AbstractUser

from django.db import models


class User(AbstractUser):
    photo = models.ImageField(
        max_length=255,
        upload_to="users/user/profile_photo",
        blank=True,
        null=True,
    )

apps/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class RegisterUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            "username",
            "email",
            "password1",
            "password2",
            "photo",
        )

apps/users/views.py
from django.contrib.auth import get_user_model, login
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import LoginView
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import FormView, UpdateView, DetailView

from apps.users.forms import RegisterUserForm


User = get_user_model()


class RegisterFormView(FormView):
    form_class = RegisterUserForm
    template_name = "registration/register.html"
    success_url = reverse_lazy("root:home_page")

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect("root:home_page")


class LoginFormView(LoginView):
    form_class = AuthenticationForm
    template_name = "registration/login.html"


class UserDetailView(DetailView):
    model = User


class UserUpdateView(UpdateView):
    model = User
    fields = (
        "username",
        "first_name",
        "last_name",
        "email",
        "photo",
    )

    success_url = reverse_lazy("root:home_page")

apps/templates/users/user_detail.html
{% extends '_helpers/_base.html' %}

{% block content %}

    <h1>Welcome to your profile, {{ object.username }}</h1>
    {% if user.photo %}
        <img src="{{ user.photo.url }}" alt="Photo" width="150">
    {% endif %}

    {% if object.first_name %}
        <p>First name : {{ object.first_name }}</p>
    {% else %}
        <p>First name: "You can add this info"</p>
    {% endif %}

    {% if object.last_name %}
        <p>Last name : {{ object.last_name }}</p>
    {% else %}
        <p>Last name: "You can add this info"</p>
    {% endif %}

    <p>Email : {{ object.email }}</p>

    <div class="my-elements-contols">
        <a href="{% url 'users:update_profile' pk=user.id %}">
            <button class="btn btn-warning">
                Edit Profile
            </button>
        </a>
    </div>
{% endblock %}

apps/templates/users/user_form.html
{% extends '_helpers/_base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy}}
        <button type="submit" class="btn btn-success">
            Submit
        </button>
    </form>
{% endblock %}