Hillel_hm8_django/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

apps/contacts/urls.py
from django.urls import path
from apps.contacts import views


app_name = "contacts"

urlpatterns = [
    path("contacts_list", views.list_of_contacts, name="contacts_list"),
    path("contact_details/<int:pk>", views.ContactDetailView.as_view(), name="contact_detail"),
    path("contact_create", views.ContactCreateView.as_view(), name="contact_create"),
    path("contact_update/<int:pk>", views.ContactUpdateView.as_view(), name="contact_update"),
    path("contact_delete/<int:pk>", views.ContactDeleteView.as_view(), name="contact_delete"),
]

apps/first_example/urls.py
# from django.contrib.auth.decorators import login_required
from django.urls import path
import apps.first_example.views as views

app_name = "first_example"

urlpatterns = [
    path("greetings", views.greetings_with_name_and_age, name="greetings_default"),
    path("users_accounts", views.create_users_accounts, name="users_accounts"),
    path("users_accounts_amount/<int:amount>", views.create_users_accounts_amount, name="users_accounts_amount"),
]

apps/sessions_example/urls.py
from django.urls import path
from apps.sessions_example import views

app_name = "sessions_example"

urlpatterns = [
    path("", views.SessionExampleView.as_view(), name="index"),
]

apps/users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginFormView.as_view(), name="login"),
    path("signup/", views.RegisterFormView.as_view(), name="signup"),
    path("update_profile/<int:pk>", views.UserUpdateView.as_view(), name="update_profile"),
    path("profile/<int:pk>", views.UserDetailView.as_view(), name="profile"),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("accounts/", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls),
    path("first_example/", include("apps.first_example.urls")),
    path("contacts/", include("apps.contacts.urls")),
    path("sessions_example/", include("apps.sessions_example.urls")),
    path("users/", include("apps.users.urls")),
    path("requests/", include("apps.logger_middleware.urls")),
    path("", include("apps.first_example.root_urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/templates/_helpers/_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
<link>
    <meta charset="UTF-8">
    <title>{{ Title }}</title>

    {# Add favico #}
    <link rel="icon" type="image" href="{% static "./favico/favico.ico" %}">

    {# Connect Bootstrap - BEGIN #}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script>
    {# Connect Bootstrap - END #}

    <link
    href="{% static 'styles/index.css' %}"
    rel="stylesheet">
</head>
<body>
<div class="container-fluid">
{% include '_helpers/_header.html' %}
{% block content %}
    <div>
        <p>This is _base.html, block "content"</p>
    </div>
{% endblock %}
</div>
</body>
</html>

apps/templates/_helpers/_header.html
<header>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div>
            <object
                type="image/svg+xml"
                data="/static/logo/logo.svg">
            </object>
        </div>
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}">Admin panel</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'root:home_page' %}">Home Page</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'first_example:greetings_default' %}">About me</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'first_example:users_accounts' %}">Create users accounts</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'first_example:users_accounts_amount' amount=5 %}">Create users accounts with amount</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'contacts:contacts_list' %}">Generator of contacts</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'sessions_example:index' %}">Sessions</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'users:profile' pk=user.id %}">My profile</a>
        </li>
        {% endif %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'requests:requests_menu' %}">Requests menu</a>
        </li>
    </ul>
    </nav>

    {% if user.is_authenticated %}
        {{ user.username }}
        <a href="{% url 'logout' %}">Logout</a>
    {% else%}
        <a href="{% url 'users:login' %}">Login</a>
        <p>You don't have an account ? <a href="{% url 'users:signup' %}">Create it !</a></p>
    {% endif %}
</header>